server:
  port: 10001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: config-server #别名，显示在eureka页面中，随意
  client:
    service-url:
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xukangqi/bankConfig
