server:
  port: 9001

spring:
  application:
    name: demoProvider #服务名,用来调用
  profiles:
    active:
      default
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
g