server:
  port: 9001

spring:
  application:
    name: demoProvider #服务名,用来调用
  profiles:
    active:
      default
eureka:
  instance:
    prefer-ip-address: true
    instance-id: DemoProvider9001 #别名，显示在eureka页面中，随意
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:8001/eureka/
=======
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
>>>>>>> d2879817295ef77330414de00ba168de9c735ec4
