server:
  port: 9002
spring:
  application:
    name: demoConsumer #服务名,用来注册
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: demoConsumer9002 #别名，显示在eureka页面中，随意
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


feign:
  hystrix:
    enabled: true