server:
  port: 9002
spring:
  application:
    name: demoConsumer #服务名,用来注册
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
#    hostname: democonsumer
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:8001/eureka/


=======
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
>>>>>>> d2879817295ef77330414de00ba168de9c735ec4
feign:
  hystrix:
    enabled: true