server:
  port: 8003
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eurekaserver3
  client:
    service-url:
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5
    enable-self-preservation: false

info:
  name: bank-eureka003
