server:
  port: 8003
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eureka003
  client:
    service-url:
      defaultZone: http://eureka001:8001/eureka/,http://eureka002:8002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5

info:
  name: bank-eureka003
