apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
    tier: backend
spec:
  selector:
    matchLabels:
      app: configserver
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
        tier: backend
    spec:
      containers:
        - name: configserver
          image: bank/configserver:1.0
          ports:
            - containerPort: 10001
          env:
            - name: EUREKASERVER_URI
              # value: http://eurekasingle:8004/eureka/
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "10001"
---

apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 10001
      targetPort: 10001
  selector:
    app: configserver
    tier: backend