apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-consumer
  labels:
    app: demo-consumer
    tier: backend
spec:
  selector:
    matchLabels:
      app: demo-consumer
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-consumer
        tier: backend
    spec:
      containers:
        - name: demo-consumer
          image: bank/demo-consumer:1.0
          ports:
            - containerPort: 9002
          env:
            - name: EUREKASERVER_URI
              # value: http://eurekasingle:8004/eureka/
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "9002"
---

apiVersion: v1
kind: Service
metadata:
  name: demo-consumer
  labels:
    app: demo-consumer
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: demo-consumer
    tier: backend