apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver1
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: eureka
      role: peer1
      tier: server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
        role: peer1
        tier: server
    spec:
      containers:
      - name: master
        image: bank/eureka001:1.0
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver1
  labels:
    app: eureka
    role: peer1
    tier: server
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: eureka
    role: peer1
    tier: server