apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver3
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: eureka
      role: peer3
      tier: server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
        role: peer3
        tier: server
    spec:
      containers:
      - name: master
        image: bank/eureka003:1.0
        ports:
        - containerPort: 8003

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver3
  labels:
    app: eureka
    role: peer3
    tier: server
spec:
  type: NodePort
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: eureka
    role: peer3
    tier: server