apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver2
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: eureka
      role: peer2
      tier: server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
        role: peer2
        tier: server
    spec:
      containers:
      - name: master
        image: bank/eureka002:1.0
        ports:
        - containerPort: 8002
        env:
          - name: EUREKASERVER_URI
            # value: http://eurekasingle:8004/eureka/
            value: http://eurekaserver1:8001/eureka/,http://eurekaserver3:8003/eureka/
          - name: SERVER_PORT
            value: "8002"

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver2
  labels:
    app: eureka
    role: peer2
    tier: server
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: eureka
    role: peer2
    tier: server