apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekasingle
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: eureka
      role: single
      tier: server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
        role: single
        tier: server
    spec:
      containers:
      - name: master
        image: bank/eurekasingle:1.0
        ports:
        - containerPort: 8004

---

apiVersion: v1
kind: Service
metadata:
  name: eurekasingle
  labels:
    app: eureka
    role: single
    tier: server
spec:
  type: NodePort
  ports:
  - port: 8004
    targetPort: 8004
  selector:
    app: eureka
    role: single
    tier: server