apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-applyment
  labels:
    app: loan-applyment
    tier: backend
spec:
  selector:
    matchLabels:
      app: loan-applyment
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: loan-applyment
        tier: backend
    spec:
      containers:
        - name: loan-applyment
          image: bank/loan-applyment:1.0
          ports:
            - containerPort: 7003
          env:
            - name: EUREKASERVER_URI
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "7003"
            - name: DATABASE_URI
              value: jdbc:mysql://loan-applyment-database:3306/bank?useUnicode=true&characterEncoding=utf8
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"