apiVersion: apps/v1
kind: Deployment
metadata:
  name: remit-database
  labels:
    app: remit-database
    tier: backend
spec:
  selector:
    matchLabels:
      app: remit-database
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: remit-database
        tier: backend
    spec:
      containers:
        - name: remit-database
          image: mysql:5.6
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sqlscript-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: data-volume
              mountPath: /var/lib/mysql/
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: LANG
              value: C.UTF-8
      volumes:
        - name: sqlscript-volume
          hostPath:
            path: /Users/xukangqi/Desktop/BankSystem/compose/remitsqlscript
        - name: data-volume
          hostPath:
            path: /Users/xukangqi/Desktop/BankSystem/compose/remitdata
---
apiVersion: v1
kind: Service
metadata:
  name: remit-database
  labels:
    app: remit-database
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: remit-database
    tier: backend