apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-remit-hotspot
  labels:
    app: service-remit-hotspot
    tier: backend
spec:
  selector:
    matchLabels:
      app: service-remit-hotspot
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: service-remit-hotspot
        tier: backend
    spec:
      containers:
        - name: service-remit-hotspot
          image: bank/Service-Remit-Hotspot:1.0
          ports:
            - containerPort: 9104
          env:
            - name: EUREKASERVER_URI
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "9104"
            - name: DATABASE_URI
              value: jdbc:mysql://service-database:3306/bank?useUnicode=true&characterEncoding=utf8
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-remit-normal
  labels:
    app: service-remit-normal
    tier: backend
spec:
  selector:
    matchLabels:
      app: service-remit-normal
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: service-remit-normal
        tier: backend
    spec:
      containers:
        - name: service-remit-normal
          image: bank/Service-Remit-Normal:1.0
          ports:
            - containerPort: 9103
          env:
            - name: EUREKASERVER_URI
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "9103"
            - name: DATABASE_URI
              value: jdbc:mysql://remit-database:3306/bank?useUnicode=true&characterEncoding=utf8
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"
