apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-login
  labels:
    app: user-login
    tier: backend
spec:
  selector:
    matchLabels:
      app: user-login
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-login
        tier: backend
    spec:
      containers:
        - name: user-login
          image: bank/user-login:1.0
          ports:
            - containerPort: 3001
          env:
            - name: EUREKASERVER_URI
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "3001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  selector:
    matchLabels:
      app: user-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: user-service
          image: bank/user-service:1.0
          ports:
            - containerPort: 3002
          env:
            - name: EUREKASERVER_URI
              value: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
            - name: SERVER_PORT
              value: "3002"
