server:
  port: 8004
spring:
  application:
    name: eurekasingle
eureka:
  instance:
    hostname: eureka-single
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     defaultZone: http://localhost:8004
  server:
    waitTimeInMsWhenSyncEmpty: 30


info:
  name: eureka-single
