server:
  port: 8002
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eureka002
  client:
    service-url:
      defaultZone: http://eureka001:8001/eureka/,http://eureka003:8003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5
info:
  name: bank-eureka002
