server:
  port: 8002
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eurekaserver2
  client:
    service-url:
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver3:8003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5
    enable-self-preservation: false
info:
  name: bank-eureka002
