server:
  port: 7003

spring:
  application:
    name: loan-applyment #服务名,用来调用
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

  datasource:
    username: root
    password: wh123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=utf8&useSSL=false
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: loan-applyment7003 #别名，显示在eureka页面中，随意
  client:
    service-url:
      defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml