# springboot配置文件

# 实体类包路径，mapper xml 映射文件
mybatis:
  type-aliases-package: com.bank.customergetaccounts.pojo
  mapper-locations: classpath:mapper/*.xml


server:
  port: 3004

spring:
  profiles:
    active: jdbc
  cloud:
    config:
      enabled: true
  application:
    name: customer-getaccounts  #服务名，用来调用

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    defaultZone: http://eurekaserver1:8001/eureka/,http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
feign:
  hystrix:
    enabled: true

info:
  name: customer-getaccounts
