server:
  port: 8001
eureka:
  instance:
    hostname: eureka001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka003:8001,http://eureka002:8002,http://eureka003:8003
  server:
    wait-time-in-ms-when-sync-empty: 5
