server:
  port: 8001
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eureka001
  client:
    service-url:
      defaultZone: http://eureka002:8002/eureka/,http://eureka003:8003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5

info:
  name: bank-eureka001
