server:
  port: 8001
spring:
  application:
    name: eureka-cluster
eureka:
  instance:
    hostname: eurekaserver1
  client:
    service-url:
      defaultZone: http://eurekaserver2:8002/eureka/,http://eurekaserver3:8003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5
    enable-self-preservation: false
info:
  name: bank-eureka001
